tbs:
  framework:
    base:
      lock:
        proxy-lock-type: tbs.framework.redis.impls.lock.RedissonLockImpl
        proxy-lock-time-unit: minutes
        proxy-lock-timeout: 1
      uuid-provider: tbs.framework.utils.impls.SnowFlakeUUID
    locale:
      type: header
      value: X-LANG
    auth:
      token-picker: tbs.framework.auth.interfaces.impls.tokenPickers.HeaderRequestTokenPicker
      enable-cors: true
      enable-annotation-permission-validator: true
      auth-path-pattern:
        [
          "/api/**"
        ]
    swagger:
      base-package: com.example.demo
    sql:
      enable-log-interceptor: true
    mq:
      consumer-manager: tbs.framework.mq.consumer.manager.impls.PatternConsumerManager
      auto-start-center: true
      event-impl: tbs.framework.mq.event.impls.LogMqEvent
    redis:
      mq:
        message-serializer-class: org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: '!Ty1997923'
    url: jdbc:mysql://192.168.50.197:3306/easy_home_money?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useUnicode=true
    username: root
  redis:
    password: '123456'
    lettuce:
      pool:
        enabled: true
        max-active: 16
        max-idle: 3
        min-idle: 0
        time-between-eviction-runs: 1s
    host: 192.168.50.197
  messages:
    basename: i18n/i18n
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
server:
  port: 8082

mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    tbs.framework: info
    com.example.demo: info