tbs:
  framework:
    base:
      lock:
        lock-type: tbs.framework.base.lock.impls.JdkLock
        lock-timeout: 3
        lock-time-unit: seconds
        lock-impl: java.util.concurrent.locks.ReentrantLock
    locale:
      type: cookie
      value: X-LANG
    auth:
      token-pick-url-patterns: [
        "/api/**"
      ]
      token-picker: tbs.framework.auth.interfaces.impls.tokenPickers.ParameterRequestTokenPicker
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: '!Ty1997923'
    url: jdbc:p6spy:mysql://192.168.50.197:3306/easy_home_money?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useUnicode=true
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root

  messages:
    basename: i18n/i18n
server:
  port: 8081

mybatis:
  configuration:
     map-underscore-to-camel-case: true