tbs:
  framework:
    base:
      lock:
        proxy-lock-time-unit: minutes
        proxy-lock-timeout: 1
        lock-provider: tbs.framework.zookeeper.locks.ZooKeeperLockProvider
      uuid-provider: tbs.framework.utils.impls.SnowFlakeUUID
      logger-provider: tbs.framework.utils.impls.Slf4JLoggerFactory
    locale:
      type: header
      value: X-LANG
    auth:
      token-picker: tbs.framework.auth.interfaces.impls.tokenPickers.HeaderRequestTokenPicker
      enable-cors: true
      enable-annotation-permission-validator: true
      auth-path-pattern:
        [
          "/api/**"
        ]
    swagger:
      base-package: com.example.demo
    sql:
      enable-log-interceptor: false
    mq:
      consumer-manager: tbs.framework.mq.consumer.manager.impls.PatternConsumerManager
      auto-start-center: true
      rabbit:
        rebuild-exchange-and-queue: true
        passive-reception: true
      task-block-alive-time: 1m
      task-block-clean-interval: 10s
    redis:
      mq:
        message-serializer-class: org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer

    async:
      task:
        receipt-broker: tbs.framework.cache.impls.CachedAsyncReceiptBroker
        receipt-timeout: 30
    cache:
      cache-service-class: tbs.framework.redis.cache.impls.services.RedisCacheServiceImpl
    zookeeper:
      registry-address: 127.0.0.1:2181
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: '123456'
    url: jdbc:mysql://127.0.0.1:4000/easy_home_money?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useUnicode=true
    username: root
  redis:
    password: '123456'
    lettuce:
      pool:
        enabled: true
        max-active: 16
        max-idle: 3
        min-idle: 0
        time-between-eviction-runs: 1s
    host: 127.0.0.1
  messages:
    basename: i18n/i18n
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
server:
  port: 8082

mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    tbs.framework: trace
    com.example.demo: debug