tbs:
  framework:
    base:
      lock:
        proxy-lock-type: tbs.framework.redis.impls.lock.RedissonLockImpl
        proxy-lock-time-unit: minutes
        proxy-lock-timeout: 1
      uuid-provider: tbs.framework.base.utils.impls.SnowFlakeUUID
    locale:
      type: header
      value: X-LANG
    auth:
      token-picker: tbs.framework.auth.interfaces.impls.tokenPickers.HeaderRequestTokenPicker
      enable-cors: true
      enable-annotation-permission-validator: true
      auth-path-pattern:
        [
          "/api/**"
        ]
    sql:
      enable-log-interceptor: true
    mq:
      consumer-manager: tbs.framework.mq.consumer.manager.impls.PatternConsumerManager
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: '123456'
    url: jdbc:mysql://127.0.0.1:4000/easy_home_money?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useUnicode=true
    username: root
  redis:
    password: '123456'
  #  messages:
  #    basename: i18n/i18n
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
server:
  port: 8081

mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    tbs.framework: info
    sec.secpart: info